sudo: false
language: node_js
notifications:
  email: false
node_js:
  - '4.2'
  - 'stable'
before_script:
  - npm install -g istanbul
  - npm Runner-script pretest
  - npm link
script:
  - istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- --recursive
#  - katapult deploy jmversteeg/katapult-test#ci local
after_script:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js