sudo: false
language: node_js
notifications:
  email: false
node_js:
  - stable
before_script:
  - npm run-script pretest
  - npm link
script:
  - npm run test
  - git clone -b ci https://github.com/sgtlambda/katapult-test.git tmp && cd tmp && katapult package